[package]
name = "rust-raid"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.29"
tui-textarea = "0.7"
crossterm = "0.28"
toml = "0.8"
serde = { version = "1.0", features = ["derive"] }
tempfile = "3"
anyhow = "1.0"
glob = "0.3.3"
